try{
/*
 * Do not edit this file by hand
 */ 
var Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart_module = angular.module('Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart', ['adf.provider','builder','builder.components','validator.rules'])
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart', {
        title: 'Task002Start',
        editTitle :'Task002Start Settings',
        description: 'Task002Start Description',
        templateUrl: '/<<CONTEXT_ROOT>>/Task002Start/views/view.xhtml',
        controller: 'Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart_Controller',
        controllerAs: 'Task002Start',
        frameless : 'false',
        previewImage: '/<<CONTEXT_ROOT>>/images/Task002Start/default.png',
        edit: {
          templateUrl: '/<<CONTEXT_ROOT>>/Task002Start/views/settings.xhtml'
        },
        application : "TaskDevelopmentProject0001A",
        gadgetGroup: "TaskDevelopmentProject0001A",
        id: "Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart",
        widgetName : "Task002Start",
        defaults:{ "title": "Task002Start",
  	      "structure": "6-6",
  	      "rows": [{
  	        "columns": [{
  	          "styleClass": "col-md-12",
  	          "widgets": [ {
  	              "type": "Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart",
  	              "title": "",
  	              "config": {
  	            	  "params":{
  	            	         
                                },
  	            	  "title":""
  	              	}
  	            }]
  	        }]
  	      }]
  	  }
              });
  });
   if(angular.module('Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart')){
    	wmBCGadgets.requires.push('Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart');
    	
    	Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart_module.run(function(){
    		try{
	    		var dep=['builder','builder.components','validator.rules'];//define list of dependencies
	        	for(var module in dep){
	        		if(dep.hasOwnProperty(module)){
	        			angular.module(dep[module]);
	        			Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart_module.requires.push(dep[module]);
	        		}
	        	}
    		}catch(exception){
    			console.error("Gadget Exception: "+exception);
    		}
    	});
    	 
    }

}
catch(exception){
	angular.module('wmBCGadgets').run(function(dashboard){
		dashboard.widgets["Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart"]= Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart_module;
	})
	Task002Start_70c3ab05_21ce_42b9_bcb8_cd9933b72feeStart_module["error"]=exception;
	throw new GadgetException(exception);
}